language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
    - dev
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm i
script:
  - npm run lib && npm run build && sh ./scripts/git-page.sh
deploy:
  provider: pages
  name: MZI
  email: macchenjl@foxmail.com
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  on:
    branch: master
